CREATE TABLE phases (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

CREATE TABLE workouts (
    workouttitle TEXT NOT NULL,
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "phaseId" INTEGER REFERENCES phases(id) ON DELETE CASCADE NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    content TEXT DEFAULT '', 
    squatsweight INTEGER,
    benchweight INTEGER,
    deadliftweight INTEGER,
    workrating INTEGER
);  
